### ISSUE TITLE
versions > 1.32.1 fails

### ISSUE THREAD

**Issue by denise-amiga** [Hezkore/vscode-blitzmax-support#1]
version 1.32.1 runs fine, all ok.
any higher version fails.
the blitzmax's panel does not appear.
in settings, the configuration of the path gives an error, and it is not recorded -> "URI expected. URI with a scheme is expected."
and when trying to compile it gives another error -> "command 'blitzmax.buildAndRun' not found"

my system:
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:32:10.090Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.7.19-2-MANJARO

https://user-images.githubusercontent.com/1727311/103112047-fd8beb00-4652-11eb-9fd6-c6204ce05544.mp4

**Comment by Hezkore** [comment]
Hmm, I've tested on a few systems, and I'm unable to reproduce this problem.
It seems the issue is that the actual extension is not starting, only the information from the extension is loaded in.
`URI expected. URI with a scheme is expected.`  is not a problem in itself, it just means you haven't entered a valid path to your BlitzMax installation.
But the extension should display a popup asking where your BlitzMax installation is located if it's not filled in.
Which, again, makes me believe that the actual extension is never loaded in by your VS Code.
Same with `command 'blitzmax.buildAndRun' not found`, it's also an indication that the extension isn't actually loaded in, only the basic information is.

I'll continue to explore on other systems, hopefully one will exhibit the same issues.
Please post any new information regarding this issue.

**Comment by Hezkore** [comment]
Just for reference; here's how the update works for me:

https://user-images.githubusercontent.com/1727541/103251442-f4638c80-4978-11eb-95e1-64a59ec6868d.mp4

**Comment by denise-amiga** [comment]
I have removed the vscode configuration folder, to start from scratch.
I have been installing from 1.32.1 onwards and I am sending you a screenshot of all the steps.
### Version 1.32.1

1. Settings
![v1 32 1_settings](https://user-images.githubusercontent.com/1727311/103276367-9c537700-49c6-11eb-9b2e-a6cc687d1121.png)

2. Panel
![v1 32 1_panel](https://user-images.githubusercontent.com/1727311/103276352-952c6900-49c6-11eb-85fe-17153c04ac32.png)

3. Run
![v1 32 1_run](https://user-images.githubusercontent.com/1727311/103276357-98275980-49c6-11eb-8313-03683e322e31.png)
All ok

### Version 2.0.0

1. Settings  (only path?)
![v2 0 0_settings](https://user-images.githubusercontent.com/1727311/103277161-ae361980-49c8-11eb-81e2-930fdba65e98.png)

2. Switch to code tab. Ok the LSP is missing, it shows the error
![v2 0 0_panel](https://user-images.githubusercontent.com/1727311/103277147-a4acb180-49c8-11eb-8e58-75d886c064c6.png)
![v2 0 0_panel1](https://user-images.githubusercontent.com/1727311/103277154-a8403880-49c8-11eb-9c61-b029d7d62a88.png)

3. LSP compiled, a panel like version 1.32.1 does not appear, but a new window appears :+1:  (there are no quick buttons to build/debug/run)
![v2 0 0_panel2](https://user-images.githubusercontent.com/1727311/103277158-ab3b2900-49c8-11eb-8320-e2f0cab7958f.png)

### Version 2.0.1
like 2.0.0

### Version 2.1.0

1. Settings (path is clean)
![v2 1 0_settings0](https://user-images.githubusercontent.com/1727311/103279948-6ebefb80-49cf-11eb-8958-12e4a7a4e668.png)
  1.1. path filled
![v2 1 0_settings1](https://user-images.githubusercontent.com/1727311/103279951-71215580-49cf-11eb-9bf9-2174ded1b0df.png)

2. Swith to code tab, Select Blitzmax panel, the panel is empty.
![v2 1 0_panel](https://user-images.githubusercontent.com/1727311/103279943-6961b100-49cf-11eb-9253-5cf0d38ebbf6.png)

3. Run. show "command 'blitzmax.buildAndRun' not found" error 
![v2 1 0_run](https://user-images.githubusercontent.com/1727311/103279944-6c5ca180-49cf-11eb-9cfc-cc76673b2a5e.png)

4. The path has not been recorded
![v2 1 0_settings2](https://user-images.githubusercontent.com/1727311/103279960-741c4600-49cf-11eb-99cc-b8b6b6df6d81.png)

### Version 2.1.1
like 2.1.0

Right now I don't have access to any windows machine.
I am sending you the compressed extensions, in case you can check if they are properly installed/downloaded in linux
[https://mega.nz/file/Ll50TRIB#rDbrBVI_q7ZFYNaD85pq6EhRlSl8dV0DkGRm3bE48IE](url)

**Comment by Hezkore** [comment]
I installed Manjaro myself and tested this out.
Can you give version 2.1.2 a try?

Remember that version 2.0 and above will lack some features from the previous versions.
2.0 is a total re-write with new modules and methods of doing things.
Things might be a bit rough right now, but it will eventually function a lot better and have a proper debugger implemented.
For example the auto-complete will not function right now without a proper LSP installed.
For LSP issues you should turn to [https://github.com/GWRon/bmxng-languageserver](https://github.com/GWRon/bmxng-languageserver).

**Comment by denise-amiga** [comment]
ok. 2.1.2 runs fine +1
thx and happy new year :D
