### ISSUE TITLE
extern functions not supported properly in outline view

### ISSUE THREAD

**Issue by ProPuke** [Hezkore/vscode-blitzmax-support#15]
![image](https://user-images.githubusercontent.com/105934/138604900-6d7d60ae-cc72-46fa-b111-102a75c45d11.png)

It's a tidal _waave!_

(`Function`s in `Extern` blocks don't have an `End Function`)

**Comment by GWRon** [comment]
Looks like a stairway to "heaven"...if you prefer rtl writing ...and upwards ;-)

**Comment by Hezkore** [comment]
Yeah the same thing happens with Abstract methods as well.
I'd like to completely remove the built-in outliner once the LSP is working.
